if(NOT FFTW_LIBRARY OR NOT FFTW_INCLUDE_DIR)
    find_library(FFTW_LIBRARY NAMES fftw3f fftw3f-3)
    find_path(FFTW_INCLUDE_DIR fftw3.h)
    message( STATUS "FFTW library: ${FFTW_LIBRARY}" )
    message( STATUS "FFTW include dir: ${FFTW_INCLUDE_DIR}" )
endif()

if(NOT SNDFILE_LIBRARY OR NOT SNDFILE_INCLUDE_DIR)
    find_library(SNDFILE_LIBRARY NAMES sndfile sndfile-1)
    find_path(SNDFILE_INCLUDE_DIR sndfile.h)
    message( STATUS "sndfile library: ${SNDFILE_LIBRARY}" )
    message( STATUS "sndfile include dir: ${SNDFILE_INCLUDE_DIR}" )
endif()

if(NOT SAMPLERATE_LIBRARY OR NOT SAMPLERATE_INCLUDE_DIR)
    find_library(SAMPLERATE_LIBRARY NAMES samplerate samplerate-0)
    find_path(SAMPLERATE_INCLUDE_DIR samplerate.h)
    message( STATUS "samplerate library: ${SAMPLERATE_LIBRARY}" )
    message( STATUS "samplerate include dir: ${SAMPLERATE_INCLUDE_DIR}" )
endif()

if(NOT VAMP_SDK_LIBRARY OR NOT VAMP_SDK_INCLUDE_DIR)
    find_library(VAMP_SDK_LIBRARY vamp-sdk)
    find_path(VAMP_SDK_INCLUDE_DIR vamp-sdk/vamp-sdk.h)
    message( STATUS "vamp-sdk library: ${VAMP_SDK_LIBRARY}" )
    message( STATUS "vamp-sdk include dir: ${VAMP_SDK_INCLUDE_DIR}" )
endif()
